### PR TITLE
Replace diagrams with mermaid.js

### LINKED ISSUE #36: Redraw all explanations for a more uniform look
This should be added again.

File lifecycle

### PR DESCRIPTION
**Pull request by martialblog**
Diagrams are now rendered with mermaid.js - with this change we can now more easily modify them in the future.

All diagrams can be written in mermaid and then be rendered with the mermaid-cli

```
cat _images/mermaid/central-vcs.mmd
graph RL
    subgraph CentralVCS
    C{{Version DB}}
    end
    C -->|Client A| D[File]
    C -->|Client B| E[File]
    C -->|Client C| F[File]

# Can also render svg
docker run -u `id -u`:`id -g` --rm -v $(pwd)/_images/mermaid:/data minlag/mermaid-cli -e png -i "/data/central-vcs.mmd"
``` 

Fixes #36

### CODE REVIEW

**Comment by martialblog** [comment]
@theFeu @htriem @mocdaniel I'd love some feedback on this. :chart_with_upwards_trend:

**Comment by theFeu** [comment]
ad discussed offline
@martialblog will still update the gitflow workflow graphics so the colours match

**Comment by martialblog** [comment]
@theFeu I updated the images so that the colors stay the same.

**Comment by theFeu** [comment]
I'll assume you looked at it and would say it's ready to merge then!

**Comment by martialblog** [comment]
I will give it a try

**Comment by theFeu** [comment]
If you want to, you can leave it to me, I have the right tools.
I'd do it tomorrow at lunch.

**Comment by martialblog** [comment]
I added some adjustments on a new commit

**Comment by martialblog** [comment]
@theFeu I'm waiting on your go to shipit :shipit:

**Comment by theFeu** [comment]
GOGO

**Comment by martialblog** [comment]
Houston we are go for merge :rocket:

**Pull request merged**
