### PR TITLE
Use git push -u origin -all

### LINKED ISSUE #153: Change the slide on connecting the repo with remote to correspond to the GitLab suggestions
Push an existing Git repository
```
cd existing_repo
git remote rename origin old-origin
git remote add origin https://11697-gitlab-0b092-web.nws.netways.de/gitlab-instance-249a55c0/training.git
git push -u origin --all
git push -u origin --tags
```

### PR DESCRIPTION
**Pull request by htriem**
Fixes #153.

I don't think that's everything, I'm not too sure either what would be missing or where exactly you're looking for that replacement.

### CODE REVIEW

**Comment by martialblog** [comment]
I think what @theFeu meant is that when you create a now Project in GitLab, you get some command suggestions i.e. 

Push an existing Git repository

```
cd existing_repo
git remote rename origin old-origin
git remote add origin git@git.example.com/deleteme.git
git push -u origin --all
git push -u origin --tags
```

And we should add that in the slides. Right?

**Comment by theFeu** [comment]
The text from GitLab is:

```
cd existing_repo
git remote rename origin old-origin
git remote add origin git@git.example.com/deleteme.git
git push -u origin --all
git push -u origin --tags
```


What we want is

```
cd existing_repo
git remote add origin git@git.example.com/deleteme.git
git push -u origin --all
git push -u origin --tags
```

So the suggestion without the `git remote rename origin old-origin`

**Review by mocdaniel — APPROVED** [review]

**Comment by martialblog** [comment]
@theFeu I updated the slides. Can you have a look pleaze.

**Comment by theFeu** [comment]
This change only affects the handout and not the presentation - was this intentional?

**Comment by martialblog** [comment]
I think since we have the push in the "Lab 7.3: Add the repository as remote origin"

**Comment by martialblog** [comment]
@theFeu Changed as discussed. Hint, I removed the --tags push since it's in the lab 8.3

**Comment by martialblog** [comment]
We good on this? I think this looks alright now

**Pull request merged**
