### PR TITLE
Replace old images with Markdown code

### LINKED ISSUE #150: Replace some of the "michi" Images with Markdown
Some of the old images don't have the best resolution and color. Could be replaced with Markdown Code blocks

### PR DESCRIPTION
**Pull request by martialblog**
Replaced the old low res images with Markdown. 

Fixes #150

### CODE REVIEW

**Comment by theFeu** [comment]
image

There is no highlighting for those snippets, which kind of defeats the point of them showing the highlighting...

**Comment by martialblog** [comment]
I thought the point was the Shell integration, changing the $PS1 and so on

**Comment by theFeu** [comment]
At least the slide I took the screenshot of is about showcasing the shell integration.
In my eyes it is pretty important to have some valuable highlighting there, so I would strongly prefer replacing the screenshot  with a higher res one.

**Comment by martialblog** [comment]
@theFeu We could use HTML

```
<p><span style="color:blue">training@netways</span> <span style="color:green">~</span>$</span> cd git/icinga</p>
<p><span style="color:blue">training@netways</span> <span style="color:green">~/git/icinga</span> <span style="color:red">(fix/issue-5=) $</span></p>
```

screenshot_2022-09-21-102636

**Comment by theFeu** [comment]
That's actually a brilliant idea!
Did you test wether our renderer can display that?

**Comment by martialblog** [comment]
I just added an HTML example that looks like this. HTML and PDF rendering look alright to me

screenshot_2022-09-21-110536

**Comment by theFeu** [comment]
Looks good to me so far :)

Could you change it to:

```
training@netways ~ $ cd repository
training@netways ~/repository (feature/docs) $ 
```

I think that would fit the training environment a bit better :)
Great work!

**Comment by martialblog** [comment]
Done :heavy_check_mark:

**Pull request merged**
