### PR TITLE
Rename master to main

### LINKED ISSUE #129: Rename master to main everywhere in the training.

### PR DESCRIPTION
**Pull request by theFeu**
Fixes #129

### CODE REVIEW

**Comment by theFeu** [comment]
@htriem Do you think it would make sense to add a slide or a note that acknowledges the change?

**Comment by theFeu** [comment]
This change will only take effect in the self hostet instances from 22 June 2021 onwards, so there's a due date in this one now :)

**Comment by dnsmichi** [comment]
Recommend linking https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/ as SSoT. Change affects both, self-hosted, and newly created projects on GitLab.com.

**Review by martialblog — APPROVED** [review]
LGTM :+1:

**Comment by martialblog** [comment]
I think adding the global defaultBranch is a good idea. Plus, we should maybe mention that historically it was `master` and many vendors are in the progress of moving to `main`

**Comment by martialblog** [comment]
I just rebased the branch

**Comment by theFeu** [comment]
@martialblog  - Been a bit out of the loop on this one, did we change the provisioning yet?
Else I'll give it a shot now :)

**Comment by martialblog** [comment]
@theFeu I don't know what version the NWS GitLab instances currently have. Nonetheless we should add your suggestion `git config --global init.defaultBranch main`

**Comment by theFeu** [comment]
The GitLab instances already are at a version that prefers main, it's only our terminal machines that don't have it yet.
And since we push the local master to the remote, we also have a master in the GitLab - should be fixed in the provisioning.
I'll look into it!

**Comment by theFeu** [comment]
Done!

**Comment by martialblog** [comment]
:dancers:

**Pull request merged**
