### PR TITLE
Switch out images

### LINKED ISSUE #150: Replace some of the "michi" Images with Markdown
Some of the old images don't have the best resolution and color. Could be replaced with Markdown Code blocks

### PR DESCRIPTION
**Pull request by theFeu**
2 Screenshots still missing, will be provided by @htriem 

Fixes #150

### CODE REVIEW

**Review by martialblog — APPROVED** [review]
LGTM :+1:

**Comment by martialblog** [comment]
@theFeu Are there still screens missing? If so which ones?

**Comment by theFeu** [comment]
There are still some missing from the command line screenshots - that need some better contrast, as they are hard to read - and we also wanted to take new screenshots of the GUIs

**Comment by martialblog** [comment]
i think these are some that should be replaced

- git_configuration_gitconfig_user.png
- git_installation_cli_example.png
- git_branch_tracking.png

**Comment by theFeu** [comment]
I'll have a look at them after the training :)

**Comment by martialblog** [comment]
@theFeu I just added some changes in a new PR. 

This one is good to go I think. :shipit:

**Comment by martialblog** [comment]
- Should be updated https://github.com/NETWAYS/gitlab-training/blob/master/_images/integrations/git_integrations_ide_visualstudio.png

**Comment by theFeu** [comment]
Do we want to use the screenshot provided by cstein?

**Comment by martialblog** [comment]
I think the screenshot by cstein will do just fine. Should I push it to this branch?

**Comment by theFeu** [comment]
I just had another look and realised that he is using dark mode. It's not that I am not a fan of dark mode, but I am not sure how much of a good idea it is to have it on the presenter (see @htriem s dark mode the other day)...

**Comment by martialblog** [comment]
Since it's just a screen to show that "yo there is integration for editors" I would be fine with the dark mode. That being said, the screens before and after are taken on a Mac with a light theme... sooo :shrug:

**Comment by martialblog** [comment]
@theFeu I updated the VS Code screenshot. Is this PR good to go?

**Comment by theFeu** [comment]
Sure, let's get this merged

**Pull request merged**
