### PR TITLE
[Draft] Normalize use of AE and BE

### PR DESCRIPTION
**Pull request by martialblog**
- analyse is BE, rest of the training use AE

### CODE REVIEW

**Comment by martialblog** [comment]
@mocdaniel too nitpicky?

**Comment by mocdaniel** [comment]
I like the idea, coherent styling, wording, etc. is definitely important.

**Comment by theFeu** [comment]
We should definitely do that. I usually don't notice if something is different in AE, so that's probably on me.
So if you notice any typos of that nature, feel free to just do that and merge to master 👍

**Comment by martialblog** [comment]
Might add some stuff later. Work in progress :construction:

**Comment by martialblog** [comment]
Didn't see any more obvious uses of BE. :shipit:

**Pull request merged**
